### ISSUE TITLE
Setup WPF Project

### ISSUE THREAD

**Issue by rufer7** [Appclusive/Net.Appclusive.WPF.UI#1]
**TODOs**
* [x] Create new WPF project
* [x] Create new Unit Test project
* [x] Add WPF project reference to Unit Test project
* [x] Add license headers to classes
* [x] Activate Code Contracts on all projects
* [x] Add Unit Test for Code Contracts
* [x] Add CommonAssemblySettings
* [x] Take over code from Digital Process project
  * [x] Classes
  * [x] Test classes
  * [x] XAML files
  * [x] Necessary Resources file entries
  * [x] Necessary Messages file entries
* [x] Adjust namespaces
* [x] Integrate `MahApps.Metro`
* [x] Add JustMock
* [x] Go through errors and warnings
